version: '3'

services:
  nodejs:
    build: .
    image: paulorcvieira/app-node-dockerizando:latest
    volumes:
      - .:/workspace
    ports:
      - "3030"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    volumes:
      - ./crud-node-postgres/database:/var/lib/postgresql/data